from fastapi.testclient import TestClient

from app.core.auth import create_access_token
from app.main import app


def _headers(username: str = "owner", role: str = "owner", tenant_id: str = "default"):
    token = create_access_token(username, role=role, tenant_id=tenant_id)
    return {"Authorization": f"Bearer {token}"}


def _first_unit_id(client: TestClient, headers: dict[str, str]) -> int:
    res = client.get("/units", headers=headers)
    assert res.status_code == 200
    payload = res.json()
    assert payload
    return payload[0]["id"]


def _create_relay_device(client: TestClient, headers: dict[str, str], *, unit_id: int, external_id: str) -> int:
    res = client.post(
        "/smart/devices",
        headers=headers,
        json={
            "unit_id": unit_id,
            "provider": "mock",
            "external_id": external_id,
            "name": f"Relay {external_id}",
            "category": "smart_relay",
            "is_active": True,
            "health_status": "healthy",
        },
    )
    assert res.status_code == 200
    return res.json()["id"]


def test_scene_manual_run_dispatches_device_command_and_tracks_execution():
    with TestClient(app) as client:
        headers = _headers()
        unit_id = _first_unit_id(client, headers)
        device_id = _create_relay_device(
            client,
            headers,
            unit_id=unit_id,
            external_id="scene-relay-1",
        )

        scene_res = client.post(
            "/smart/scenes",
            headers=headers,
            json={"name": "Check-in base", "description": "Scene test", "is_active": True},
        )
        assert scene_res.status_code == 200
        scene_id = scene_res.json()["id"]

        action_res = client.post(
            f"/smart/scenes/{scene_id}/actions",
            headers=headers,
            json={
                "position": 1,
                "action_type": "device_command",
                "target_device_id": device_id,
                "payload": {"command_type": "power_on", "payload": {}},
                "is_active": True,
            },
        )
        assert action_res.status_code == 200

        run_res = client.post(
            f"/smart/scenes/{scene_id}/run",
            headers=headers,
            json={"context": {"source": "test"}},
        )
        assert run_res.status_code == 200
        execution = run_res.json()
        assert execution["scene_id"] == scene_id
        assert execution["status"] == "executed"

        cmds_res = client.get(f"/smart/devices/{device_id}/commands", headers=headers)
        assert cmds_res.status_code == 200
        commands = cmds_res.json()
        assert len(commands) >= 1
        assert commands[0]["command_type"] == "power_on"


def test_automation_rule_manual_trigger_creates_alert_and_execution():
    with TestClient(app) as client:
        headers = _headers()
        unit_id = _first_unit_id(client, headers)

        rule_res = client.post(
            "/smart/automation-rules",
            headers=headers,
            json={
                "name": "Alert on manual",
                "description": "Rule test",
                "trigger_type": "manual",
                "action_type": "create_alert",
                "target_unit_id": unit_id,
                "payload": {
                    "alert_type": "automation_test",
                    "severity": "warning",
                    "title": "Automation generated alert",
                    "description": "generated by milestone 7 test",
                },
                "is_active": True,
            },
        )
        assert rule_res.status_code == 200
        rule_id = rule_res.json()["id"]

        trigger_res = client.post(
            f"/smart/automation-rules/{rule_id}/trigger",
            headers=headers,
            json={"trigger_type": "manual", "context": {"source": "unit-test"}},
        )
        assert trigger_res.status_code == 200
        execution = trigger_res.json()
        assert execution["rule_id"] == rule_id
        assert execution["status"] == "executed"

        alerts_res = client.get("/smart/alerts?status=open", headers=headers)
        assert alerts_res.status_code == 200
        assert any(a["title"] == "Automation generated alert" for a in alerts_res.json())


def test_scene_endpoints_are_tenant_isolated():
    with TestClient(app) as client:
        headers_a = _headers(username="owner-a", tenant_id="tenant_a")
        headers_b = _headers(username="owner-b", tenant_id="tenant_b")

        created = client.post(
            "/smart/scenes",
            headers=headers_a,
            json={"name": "Tenant A scene", "description": "isolated", "is_active": True},
        )
        assert created.status_code == 200
        scene_id = created.json()["id"]

        foreign_read = client.get(f"/smart/scenes/{scene_id}", headers=headers_b)
        assert foreign_read.status_code == 404

        foreign_run = client.post(
            f"/smart/scenes/{scene_id}/run",
            headers=headers_b,
            json={"context": {}},
        )
        assert foreign_run.status_code == 404
