version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: essaouira-postgres
    environment:
      POSTGRES_DB: essa
      POSTGRES_USER: essa
      POSTGRES_PASSWORD: essa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
