from datetime import datetime, time
from typing import Optional

from fastapi import HTTPException, Request
from sqlalchemy.orm import Session

from app.domains.smart_building.service import SmartBuildingService
from app.main_types import StaffRole
from app.models.pricing_defaults import PricingDefaults
from app.models.staff_defaults import StaffDefaults
from app.models.staff_member import StaffMember
from app.models.staff_task import StaffTask

TERMINAL_TASK_STATUSES = {"done", "completed"}


# ---------- TIME HELPERS ----------


def parse_time_str(value: str | None) -> Optional[time]:
    if not value:
        return None
    value = value.strip()
    if not value:
        return None
    try:
        return datetime.strptime(value, "%H:%M").time()
    except ValueError:
        try:
            return datetime.strptime(value, "%H:%M:%S").time()
        except ValueError:
            raise HTTPException(
                status_code=400,
                detail="Formato orario non valido. Usa HH:MM o HH:MM:SS.",
            )


def format_time_value(t: Optional[time]) -> Optional[str]:
    if t is None:
        return None
    return t.strftime("%H:%M")


# ---------- DEFAULTS ----------


def get_or_create_staff_defaults(db: Session) -> StaffDefaults:
    defaults = db.query(StaffDefaults).first()
    if not defaults:
        defaults = StaffDefaults(
            cleaning_default_assignee="Operatore 1",
            cleaning_default_cost=5.0,
            cleaning_default_hours=1.0,
            currency="EUR",
        )
        db.add(defaults)
        db.commit()
        db.refresh(defaults)
    return defaults


def get_or_create_pricing_defaults(db: Session) -> PricingDefaults:
    pricing = db.query(PricingDefaults).first()
    if not pricing:
        pricing = PricingDefaults(
            default_cleaning_fee=None,
            default_city_tax_per_night=None,
            default_channel_commission_percent=None,
            currency="EUR",
        )
        db.add(pricing)
        db.commit()
        db.refresh(pricing)
    return pricing


def find_default_assignee_for_role(
    db: Session,
    role: StaffRole,
    fallback_name: str | None = None,
) -> str | None:
    member = (
        db.query(StaffMember)
        .filter(
            StaffMember.role == role.value,
            StaffMember.is_active.is_(True),
        )
        .order_by(StaffMember.id)
        .first()
    )
    if member:
        return member.name
    return fallback_name


# ---------- STAFF TASK STATUS / SMART REACTIONS ----------


def normalize_task_status(value: str | None) -> str:
    return (value or "").strip().lower()


def is_auto_booking_transition_task(task: StaffTask) -> bool:
    # PMS/Ops remains source of truth: only react to booking-linked AUTO tasks
    # generated by operational automation, not to generic/manual staff tasks.
    if task.booking_id is None or task.unit_id is None:
        return False
    notes = (task.notes or "").strip().lower()
    return notes.startswith("auto:")


def merge_notes_for_auto_task(existing_notes: str | None, incoming_notes: str | None) -> str | None:
    existing = (existing_notes or "").strip()
    incoming = (incoming_notes or "").strip()
    if not incoming:
        return existing_notes
    if incoming.lower().startswith("auto:"):
        return incoming
    if existing:
        return f"{existing} | {incoming}"
    return incoming


def trigger_smart_reaction_on_staff_task_completion(
    request: Request,
    db: Session,
    *,
    old_status: str | None,
    was_auto_task: bool,
    task: StaffTask,
) -> None:
    old_normalized = normalize_task_status(old_status)
    new_normalized = normalize_task_status(task.status)
    if new_normalized not in TERMINAL_TASK_STATUSES:
        return
    if old_normalized in TERMINAL_TASK_STATUSES:
        return

    if not was_auto_task:
        return

    task_type = (task.task_type or "").strip().lower()
    if task_type == "checkin":
        trigger_type = "booking.checked_in"
    elif task_type == "checkout":
        trigger_type = "booking.checked_out"
    else:
        return

    tenant_id = getattr(request.state, "tenant_id", None)
    if not tenant_id:
        return

    service = SmartBuildingService(db=db, tenant_id=tenant_id)
    service.trigger_rules_for_business_event(
        trigger_type=trigger_type,
        trigger_source="auto.ops.staff_task",
        context={
            "task_id": task.id,
            "booking_id": task.booking_id,
            "unit_id": task.unit_id,
            "task_type": task.task_type,
            "task_date": str(task.date) if task.date else None,
        },
        requested_by=getattr(request.state, "user", None) or "system",
    )
